version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_graduation
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_graduation
    restart: always
    ports:
      - "6375:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
