spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5435/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:defaultDevSecretKeyThatIsLongEnough_please_replace}
  access-exp: 3600000
  refresh-exp: 604800000
