spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5435/graduation_project_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true
jwt:
  secret: ${JWT_SECRET:defaultDevSecretKeyThatIsLongEnough_please_replace}
  access-exp: 3600000
  refresh-exp: 604800000