name: CI - Maven build & Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  packages: read
  issues: write
  pull-requests: write

env:
  RUN_TESTS: true # Đổi thành "false" nếu muốn bỏ qua unit tests

jobs:
  style:
    name: Check style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run Checkstyle
        run: mvn -B checkstyle:checkstyle

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: [ style ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build (with or without tests)
        run: |
          if [ "${{ env.RUN_TESTS }}" = "true" ]; then
            mvn -B clean verify jacoco:report
          else
            mvn -B clean package -DskipTests
          fi

      - name: Archive test results
        if: always() && env.RUN_TESTS == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: tests-report
          path: target/surefire-reports || target/**/surefire-reports

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: target/*.jar
